version: '3.8'

services:
  media_ms:
    build: .
    command: python manage.py runserver 0.0.0.0:8003
    volumes:
      - .:/app
    ports:
      - "8003:8003"
    depends_on:
      - rabbitmq

  celery:
    build: .
    command: celery -A media_processing_services worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - rabbitmq

  rabbitmq:
    image: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
